### ISSUE TITLE
手机显示侧边栏的选择效果问题

### ISSUE THREAD

**Issue by moonwjw** [zjhou/fufu.im#9]
- 问题：点选一个侧边栏分类A以后，再点击分类B，分类A的文字说明还在，如图：
![810452168871973628](https://user-images.githubusercontent.com/40885288/42544770-4c5335ee-84e6-11e8-9882-1d17b01ab8f1.jpg)

- 期望：手机端显示侧边栏状态只两种：1.普通状态：只普通状态的图标  2.点选高亮状态：高亮图标+高亮文字说明 

- 奖励：^3^

**Comment by zjhou** [comment]
将会按照手机版的图重新布局，此问题过期。不予解决。
